# Terminal
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set -sg escape-time 0
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Catppuccin
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{?client_prefix,#{@thm_red},#{?#{==:#{pane_mode},copy-mode},#{@thm_yellow},#{@thm_green}}}"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_number "#[bold]Tab ###I "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_current_number "#[bold]Tab ###I "
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

set -g status-left-length 0
set -g status-right ""
set -g status-right-length 100

# Sessions
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Floax
set -g @floax-bind 'p'
set -g @floax-width '85%'
set -g @floax-height '80%'
set -g @floax-title " #{pane_current_path} "
set -g @floax-change-path 'true'

# Prefix: Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Indexing
set -g base-index 1
setw -g pane-base-index 1

# Mouse
set -g mouse on

# Kill pane without confirmation
unbind x
bind x kill-pane

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Split panes in current path
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Vi copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# macOS
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Linux + Wayland
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Linux + X11
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

# Clipboard
set -g set-clipboard on
unbind -T copy-mode-vi MouseDragEnd1Pane

# Session tree
bind s choose-tree -sZ -O name

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# TPM must stay last
run '~/.config/tmux/plugins/tpm/tpm'
